name: Build, Test, and Push Docker Image

on:
  push:
    branches: [ main, "*" ]  # Runs on push to any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set branch name as tag
        run: echo "IMAGE_TAG=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t bdd-cucumber-sample .

      - name: Run Tests and Generate Reports in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/cucumber-reports:/app/cucumber-reports \
            bdd-cucumber-sample mvn test verify
          
      - name: Check report contents
        run: |
          echo "Listing contents of cucumber-reports..."
          ls -l cucumber-reports || echo "No files found."    

      - name: Upload test results
        uses: actions/upload-artifact@v4

        with:
          name: cucumber-test-report
          path: cucumber-reports/

      - name: Tag and Push Docker image
        run: |
          docker tag bdd-cucumber-sample nageshmukrambi/bdd-cucumber-sample:${{ env.IMAGE_TAG }}
          docker push nageshmukrambi/bdd-cucumber-sample:${{ env.IMAGE_TAG }}
