name: Run Cucumber Tests in Docker

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Pull Docker image
        run: docker pull nageshmukrambi/bdd-cucumber-sample:main

      - name: Create output folder
        run: mkdir -p reports

      - name: Run tests and save report
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/reports:/app/reports \
            nageshmukrambi/bdd-cucumber-sample:main

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: reports
